FROM registry.ci.openshift.org/ocp/4.6:base
COPY manifests.rhel/ /manifests/
LABEL description="This image contains the trusted keys for the updates delivered to a cluster." \
      io.openshift.release.operator=true